paginate:            5
markdown:            kramdown
highlighter:         rouge
permalink:           none
plugins:             [jekyll-paginate, jekyll-sitemap, jekyll-feed]

sass:
  sass_dir: assets/css
  style: :nested
