title:  "Pedaru"
tagline: "Fietsen"
description:

# Authors documented under _data

# Change to true for Disqus comments
disqus:
  comments: false
  disqus_shortname: ''

menu:
- {name: 'Services', folder: 'pages', file: 'services.html'}
- {name: 'Over Mij', folder: 'pages', file: 'about.html'}
- {name: 'Contact', folder: 'pages', file: 'contact.html'}

social:
- {icon: 'twitter', link: 'https://twitter.com/...'}
- {icon: 'facebook', link: 'https://www.facebook.com/...'}
- {icon: 'instagram', link: 'https://instagram.com/...'}
- {icon: 'envelope', link: 'mailto:...@gmail.com'}
- {icon: 'rss-square', link: 'feed.xml'}

# Available social icons are powered by Font Awesome, so you can use any icon that they offer
